# Generated by Django 4.1.7 on 2023-03-21 13:01

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=50)),
                ('rg_paciente', models.CharField(max_length=9, unique=True)),
                ('celular_paciente', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('data_consulta', models.DateField()),
                ('cpf_paciente', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
            ],
        ),
    ]
