# Generated by Django 4.1.7 on 2023-03-21 13:15

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf_paciente'),
        ),
    ]
