# Generated by Django 4.1.7 on 2023-03-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_areamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgencia', models.CharField(choices=[('Em Espera', 'Em Espera'), ('Não Crítico', 'Não Crítico'), ('Semicritico', 'Semicritito'), ('Crítico', 'Crítico')], default='Em Espera', max_length=15)),
                ('observacoes', models.TextField(max_length=300)),
                ('area_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.areamedica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
    ]
